# See README.md for extra documentation on the specifics of an element.
# TODO: rewrite config documentation
---
api_token: ""
api_client_id: ""
bot_user_id: 8
api_version: 9

# Switches the bot between "development" and "production" modes.
# In development mode, if devguild is set, global commands will be
# redirected to the specified guild instead.
#
# Debug mode is either on with "debug" set to true or "mode" be "development"
mode: "production"
debug: false
devguild: ""

# list of global features
# for commands, everyone can use them (no permissions possible)
# and they may be run in DMs. If a feature appears here, it will
# be global, even if specified in a guild. Features may not
# be available as global features (such as `purge`)
# NOTE: these features may take up to an hour to be registered
# NOTE: global features are enabled for @everyone, and that permission
# CANNOT be revoked.
global_features:
  - pong

# Here you configure each server. Label is the server's ID.
# Commands are disbaled for @everyone by default.
# name: Friendly name for reference, not used by the bot
# features: which features should be enabled, on top of any
#           global features
# role_perms: a list of roles and which commands they can use
# example config:
# guilds:
#   "your_guild_id_here":
#     name: "your amazing server"
#     features:
#       - purge
#     role_perms:
#       "Admin":
#         - purge
guilds:
  "your_guild_id_here":
    name: "your amazing server"
    features:
      - purge
    role_perms:
      "Admin":
        - purge

# Self-roles feature config
self_roles_channel: "self-roles"

# anything related to the community prompt
prompt:
  channel: "community-prompts"

  # top and bottom text to the prompt message
  # the prompt text given will be inbetween those
  # if you want to reference a channel or user, you need to follow
  # the proper way to reference things with their encoded IDs
  top_text: ""
  bottom_text: ""

# URLs used by various features
urls:
  mc_address_url: ""
