version: "3.9"
services:
  app:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
